config/routes.rb
Rails.application.routes.draw do

  resources :students

  get 'invoices/index'

  get 'invoices/show'

  get 'posts/index'

  resources :products
  resources :blogs

  resources :product_previews

  get 'page_controllers/index'
  get 'page_controllers/contact'
  get 'page_controllers/shop_location'
  get 'page_controllers/customer_service'
  get 'page_controllers/feature'

  get 'users/index'

  get 'users/show'

  devise_for :users
  devise_scope :user do
    root :to => "page_controllers#index"
    resources :users, :only => [:index, :show]
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
end

app/models/blog.rb
class Blog < Post
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories, :class_name => "Category", :foreign_key => "parent_id"
  belongs_to :parent_category, :class_name => "Category", :foreign_key => "parent_id"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :country_type

  has_many :addresses
  has_many :invoices

  default_scope { order(:name) }
end

app/models/country_type.rb
class CountryType < ActiveRecord::Base
  has_many :countries
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  belongs_to :shipping
  belongs_to :payment_type

  has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :invoice
  belongs_to :product
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base

  has_many :invoices
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :general_information
  belongs_to :product_preview

  has_many :product_pictures
  has_many :orders


  before_create :set_product_info

  private

  def set_product_info
    self.name = product_preview.name
    self.price = product_preview.price
  end

end

app/models/product_picture.rb
class ProductPicture < ActiveRecord::Base
  belongs_to :product
end

app/models/product_preview.rb
class ProductPreview < ActiveRecord::Base

  has_many :products
  has_many :category_products
  has_many :categories, through: :category_products

  accepts_nested_attributes_for :category_products
  accepts_nested_attributes_for :products, :allow_destroy => true

  mount_uploader :picture, PictureUploader
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :addresses
  has_many :comments
  has_many :invoices
  accepts_nested_attributes_for :addresses

  validates :username, length: { in: 4..20 }
  validates_presence_of :first_name, :last_name, :username, :sex, :birthdate
  validates :username, :uniqueness => { :case_sensitive => false }, format: {with: /\A\w+\z/}, :allow_blank => true

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end


end

app/controllers/product_previews_controller.rb
class ProductPreviewsController < ApplicationController
  def index
    @product_preview = ProductPreview.all
  end

  def show
    @product_preview = ProductPreview.find(params[:id])
  end


  def new
    @product_preview_create = ProductPreview.new
    @product_preview_create.products.build
  end

  def create
    if ProductPreview.create!(blog_params)
      redirect_to product_previews_url
    else
      render new
    end
  end


  private
  def blog_params
    params.require(:product_preview).permit(:name, :price, :picture, :products_attributes => [:id,:color,:size,:quantity,:_destroy])
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/product_previews_helper.rb
module ProductPreviewsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/product_previews/_form.html.erb
<h1 xmlns="http://www.w3.org/1999/html">Add Preview Product</h1>

<%= nested_form_for @product_preview_create, :html => {:multipart => true} do |f| %>

    <div class="form-group">
      <%= f.label :product_name %>
      <br/>
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :product_price %>
      <br/>
      <%= f.text_field :price, :class => 'form-control' %>
    </div>


    <div class="form-group">
      <%= f.fields_for Category, @product_preview_create.categories.build do |category| %>
          <%= category.label :category %>
          <br/>
          <%= category.select :name, options_for_select(Category.all.collect { |u| [u.name, u.id] }), {}, :class => 'form-control' %>
      <% end %>

    </div>

    <div class="form-group">
      <%= f.label :product_picture %>
      <br/>
      <%= f.file_field :picture, :class => 'form-control' %>
    </div>

    <h2>Stock</h2>

        <div class="row" id="addlist">
          <%= f.fields_for :products do |p| %>
              <div class="col-md-4 col-lg-4 form-group">
                <%= p.text_field :color, class: 'form-control', :label => false, :placeholder => "Color" %>
              </div>
              <div class="col-md-4 col-lg-4 form-group">
                <%= p.text_field :size, class: 'form-control', :label => false, :placeholder => "Size" %>
              </div>
              <div class="col-md-3 col-lg-3 form-group">
                <%= p.text_field :quantity, class: 'form-control', :label => false, :placeholder => "Quantity" %>
              </div>
              <div class="col-md-1 col-lg-1 form-group set-middle">
                <%= p.link_to_remove "", :class => 'btn btn-danger fa fa-times', :label => false %>
              </div>
          <% end %>
        </div>
        <div class="form-group">
          <p><%= f.link_to_add "Add a product", :products, :data => {:target => "#addlist"}, :class => 'btn btn-default' %></p>
        </div>
        <div class="form-group">
          <%= f.submit 'create', :class => 'btn btn-default' %>
        </div>
<% end %>

app/views/product_previews/index.html.erb
<h1>All Products</h1>
<% @product_preview.each do |p| %>
    <div class="col-lg-3 col-md-4 col-sm-6 each-product">
      <div class="each-product-content">
        <div><%= link_to image_tag(p.picture_url(:thumb).to_s), product_preview_path(p) %></div>
        <div><%= p.name %></div>
        <div><%= "Price : #{p.price} baht" %></div>
      </div>
    </div>
<% end %>
<%= link_to 'Create Product', new_product_preview_url %>

app/views/product_previews/new.html.erb
<%= render "product_previews/form" %>

app/views/product_previews/show.html.erb
<div class="row">

  <div class="col-lg-6 col-md-6 col-sm-6">

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag(@product_preview.picture_url.to_s, :class => 'img-responsive img-rounded') %>
          <div class="carousel-caption">
            ...
          </div>
        </div>
        <div class="item">
          <%= image_tag(@product_preview.picture_url.to_s, :class => 'img-responsive img-rounded') %>
          <div class="carousel-caption">
            ...
          </div>
        </div>
        ...
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="fa fa-chevron-left icon-prev"></span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="fa fa-chevron-right icon-next"></span>
      </a>
    </div>


  </div>

  <div class="col-lg-6">

    <h1> <%= @product_preview.name %> </h1>

    <div>
      Price  <%= @product_preview.price %>  Baht
    </div>
  </div>

  <div class="col-lg-6">
    <div>
      <ul class="nav nav-tabs" role="tablist">
        <li class="active product-menu"><a href="#home" role="tab" data-toggle="tab" class="product-menu">Home</a></li>
        <li><a href="#profile" role="tab" data-toggle="tab" class="product-menu">Profile</a></li>
        <li><a href="#messages" role="tab" data-toggle="tab" class="product-menu">Messages</a></li>
      </ul>
    </div>
    <div class="tab-content">
      <div class="tab-pane active" id="home">

      </div>
      <div class="tab-pane" id="profile">
        <p>Shipping is charged depending your location in the world.</p>

        <h3>UK</h3>

        <p>1st Class Shipping 95p + £1.00 per item (3-5 working days expected delivery)</p>

        <p>FREE UK SHIPPING for all orders over £100</p>

        <h3>EU</h3>

        <p>Royal Mail First Class £6.95</p>

        <h3>Rest of the World</h3>

        <p>Royal Mail First Class £8.95</p>
      </div>
      <div class="tab-pane" id="messages">ffff</div>
    </div>


  </div>


</div>