config/routes.rb
Rails.application.routes.draw do

  resources :students

  get 'invoices/index'

  get 'invoices/show'

  get 'posts/index'

  resources :products
  resources :blogs

  resources :product_previews

  get 'page_controllers/index'
  get 'page_controllers/contact'
  get 'page_controllers/shop_location'
  get 'page_controllers/customer_service'
  get 'page_controllers/feature'

  get 'users/index'

  get 'users/show'

  devise_for :users
  devise_scope :user do
    root :to => "page_controllers#index"
    resources :users, :only => [:index, :show]
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
end

app/models/blog.rb
class Blog < Post
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories, :class_name => "Category", :foreign_key => "parent_id"
  belongs_to :parent_category, :class_name => "Category", :foreign_key => "parent_id"
end

app/models/category_product.rb
class CategoryProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :category
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :country_type

  has_many :addresses
  has_many :invoices

  default_scope { order(:name) }
end

app/models/country_type.rb
class CountryType < ActiveRecord::Base
  has_many :countries
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  belongs_to :shipping
  belongs_to :payment_type

  has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :invoice
  belongs_to :product
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base

  has_many :invoices
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :general_information
  belongs_to :product_preview

  has_many :product_pictures
  has_many :orders


  before_create :set_product_info

  private

  def set_product_info
    self.name = product_preview.name
    self.price = product_preview.price
  end

end

app/models/product_picture.rb
class ProductPicture < ActiveRecord::Base
  belongs_to :product
end

app/models/product_preview.rb
class ProductPreview < ActiveRecord::Base

  has_many :products
  has_many :category_products
  has_many :categories, through: :category_products

  accepts_nested_attributes_for :category_products
  accepts_nested_attributes_for :products, :allow_destroy => true

  mount_uploader :picture, PictureUploader
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :addresses
  has_many :comments
  has_many :invoices
  accepts_nested_attributes_for :addresses

  validates :username, length: { in: 4..20 }
  validates_presence_of :first_name, :last_name, :username, :sex, :birthdate
  validates :username, :uniqueness => { :case_sensitive => false }, format: {with: /\A\w+\z/}, :allow_blank => true

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end


end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index

  end

  def show

  end

  def new

  end

  def create

  end



end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/products/_form.html.erb
<h1 xmlns="http://www.w3.org/1999/html">Add Preview Product</h1>

<%= nested_form_for @product_preview, :url => products_path, :html => {:multipart => true} do |f| %>

    <div class="form-group">
      <%= f.label :product_name %>
      <br/>
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :product_price %>
      <br/>
      <%= f.text_field :price, :class => 'form-control' %>
    </div>


    <div class="form-group">
      <%= f.fields_for Category, @product_preview.categories.build do |category| %>
          <%= category.label :category %>
          <br/>
          <%= category.select :name, options_for_select(Category.all.collect { |u| [u.name, u.id] }), class: 'form-control' %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :product_picture %>
      <br/>
      <%= f.file_field :picture, :class => 'form-control' %>
    </div>

    <h2>Stock</h2>

    <div class="row" id="addlist">
      <%= f.fields_for :products do |p| %>
          <div class="col-md-4 col-lg-4 form-group">
            <%= p.text_field :color, class: 'form-control', :label => false , :placeholder => "Color" %>
          </div>
          <div class="col-md-4 col-lg-4 form-group">
            <%= p.text_field :size, class: 'form-control', :label => false , :placeholder => "Size"%>
          </div>
          <div class="col-md-3 col-lg-3 form-group">
           <%= p.text_field :quantity, class: 'form-control', :label => false, :placeholder => "Quantity" %>
          </div>
          <div class="col-md-1 col-lg-1 form-group set-middle">
            <%= p.link_to_remove "X", :class => 'btn btn-danger', :label => false %>
          </div>
      <% end %>
    </div>
    <div class="form-group">
      <p><%= f.link_to_add "Add a product", :products, :data => {:target => "#addlist"}, :class => 'btn btn-default' %></p>
    </div>
    <div class="form-group">
      <%= f.submit 'create', :class => 'btn btn-default' %>
    </div>

<% end %>

app/views/products/index.html.erb
<h1>All Products</h1>
<% @products.each do |p| %>
<div class="col-lg-3 col-md-4 col-sm-6 each-product">
  <div class="each-product-content">
    <div><%= image_tag p.picture_url(:thumb).to_s %></div>
    <div><%= p.name %></div>
    <div><%= "Price : #{p.price} baht" %></div>
  </div>
</div>
<% end %>
<%= link_to 'Create Product', new_product_url %>

app/views/products/new.html.erb
<%= render "products/form" %>

app/views/products/show.html.erb
<h1>All Products</h1>
<p>Lets shop ^^</p>