config/routes.rb
Rails.application.routes.draw do

  resources :students

  get 'invoices/index'

  get 'invoices/show'

  get 'posts/index'

  resources :products
  resources :blogs

  resources :product_previews

  get 'page_controllers/index'
  get 'page_controllers/contact'
  get 'page_controllers/shop_location'
  get 'page_controllers/customer_service'
  get 'page_controllers/feature'

  get 'users/index'

  get 'users/show'

  devise_for :users
  devise_scope :user do
    root :to => "page_controllers#index"
    resources :users, :only => [:index, :show]
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
end

app/models/blog.rb
class Blog < Post
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories, :class_name => "Category", :foreign_key => "parent_id"
  belongs_to :parent_category, :class_name => "Category", :foreign_key => "parent_id"
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/country.rb
class Country < ActiveRecord::Base
  belongs_to :country_type

  has_many :addresses
  has_many :invoices

  default_scope { order(:name) }
end

app/models/country_type.rb
class CountryType < ActiveRecord::Base
  has_many :countries
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  belongs_to :user
  belongs_to :country
  belongs_to :shipping
  belongs_to :payment_type

  has_many :orders
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :invoice
  belongs_to :product
end

app/models/payment_type.rb
class PaymentType < ActiveRecord::Base

  has_many :invoices
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_many :comments
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :general_information
  belongs_to :product_preview

  has_many :product_pictures
  has_many :orders


  before_create :set_product_info

  private

  def set_product_info
    self.name = product_preview.name
    self.price = product_preview.price
  end

end

app/models/product_picture.rb
class ProductPicture < ActiveRecord::Base
  belongs_to :product
end

app/models/product_preview.rb
class ProductPreview < ActiveRecord::Base

  has_many :products
  has_many :category_products
  has_many :categories, through: :category_products

  accepts_nested_attributes_for :category_products
  accepts_nested_attributes_for :products, :allow_destroy => true

  mount_uploader :picture, PictureUploader
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :addresses
  has_many :comments
  has_many :invoices
  accepts_nested_attributes_for :addresses

  validates :username, length: { in: 4..20 }
  validates_presence_of :first_name, :last_name, :username, :sex, :birthdate
  validates :username, :uniqueness => { :case_sensitive => false }, format: {with: /\A\w+\z/}, :allow_blank => true

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end


end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Sens" %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag "application", :media => "all" %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag "application" %>
</head>
<body>
<div class="row">
  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="header-logo col-lg-3 col-md-3 col-sm-3">
        <a class="navbar-brand" href="<%= page_controllers_index_url %>">S<span class="red">E</span>NS Dessus
          Dessous</a>
      </div>
      <div class="navbar-collapse collapse navbar-responsive-collapse col-lg-7 col-md-7 col-sm-7 top-menu">
        <nav class="cl-effect-18">
          <ul>
            <li><%= link_to 'New Stuff', page_controllers_index_url %></li>
            <li><%= link_to 'Shop', product_previews_url %>
              <ul class="menu-bg">
                <li><%= link_to 'Men', product_previews_url %>
                  <ul class="menu-bg">
                    <li><%= link_to 'Top', product_previews_url %>
                    <li><%= link_to 'Bottom', product_previews_url %>
                  </ul>
                </li>
                <li><%= link_to 'Women', product_previews_url %>
                  <ul class="menu-bg">
                    <li><%= link_to 'Top', product_previews_url %>
                    <li><%= link_to 'Dress', product_previews_url %>
                    <li><%= link_to 'Bottom', product_previews_url %>
                  </ul>
                </li>
                <li><%= link_to 'Stocklist', product_previews_url %></li>
              </ul>
            </li>
            <li><%= link_to 'Feature', page_controllers_feature_url %>
              <ul class="menu-bg">
                <li><%= link_to 'Lookbook', products_url %></li>
                <li><%= link_to 'Blog', blogs_url %></li>
                <li><%= link_to 'Stars of the month', products_url %></li>
                <li><%= link_to 'News', products_url %></li>
                <li><%= link_to 'My account', products_url %></li>
              </ul>
            </li>
            <li><%= link_to 'Contact Us', page_controllers_contact_url %>
              <ul class="menu-bg">
                <li><%= link_to 'Contact Us', page_controllers_contact_url %></li>
                <li><%= link_to 'Shop Location', page_controllers_shop_location_url %></li>
                <li><%= link_to 'Customer Service', page_controllers_customer_service_url %></li>
              </ul>
            </li>
          </ul>
        </nav>
      </div>

        <% if current_user %>
            <div class="dropdown navbar-right signin-as col-lg-2 col-md-2 col-sm-2">
              Signed in as
              <%= link_to '', :class => "dropdown-toggle red signin-as", "data-toggle" => "dropdown" do %>
                  <%= current_user.username %> <span class="caret"></span>
              <% end %>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to 'My Account', edit_user_registration %></li>
                <li><%= link_to 'My Cart', product_previews_url %></li>
                <li class="divider"></li>
                <li><%= link_to 'Sign out', destroy_user_session_url, :method => :delete %></li>
              </ul>
            </div>
        <% else %>
          <div class="dropdown navbar-right signin-as col-lg-2 col-md-2 col-sm-2">
            <%= link_to '', :class => "login dropdown-toggle", "data-toggle" => "dropdown" do %>
                Login <% end %>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Login', new_user_session_url %></li>
              <li><%= link_to 'Sign Up', new_user_registration_url %></li>
              <li class="divider"></li>
              <li><%= link_to 'Sign out', :method => :delete %></li>
            </ul>
          </div>
        <% end %>

    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <%= yield %>
  </div>
  <!--/row-->

  <footer>
    <p>&copy; sens dessus dessous 2014</p>
  </footer>

</div>
<!-- /container -->

</body>
</html>